const bridge = window.AstrBotPluginPage;
const state = { groups: [], entries: [], config: {}, groupId: "", query: "", page: 1, total: 0, totalPages: 1, pageSize: 20 };
const el = Object.fromEntries(["totalMetric","groupMetric","filteredMetric","groupList","entriesTitle","searchInput","status","entryList","pageLabel","previousButton","nextButton","refreshButton","settingsButton","settingsDialog","settingsForm","closeSettingsButton","cancelSettingsButton","toast"].map(id=>[id,document.getElementById(id)]));

function unwrap(response){if(response&&response.ok===false)throw new Error(response.message||"请求失败");return response?.data??response}
function toast(message,type="ok"){el.toast.textContent=message;el.toast.className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.className="toast",2600)}
function formatTime(value){if(!value)return "未知时间";return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value*1000))}
function truncate(text,size=240){const value=String(text||"").trim();return value.length>size?`${value.slice(0,size)}…`:value||"[仅图片]"}

function renderGroups(){el.groupList.replaceChildren();const groups=[{group_id:"",amount:state.groups.reduce((n,g)=>n+g.amount,0),label:"全部群聊"},...state.groups];for(const group of groups){const button=document.createElement("button");button.className=`group-item${state.groupId===group.group_id?" active":""}`;const name=document.createElement("span");name.textContent=group.label||`群 ${group.group_id}`;const count=document.createElement("span");count.textContent=group.amount;button.append(name,count);button.addEventListener("click",()=>{state.groupId=group.group_id;state.page=1;state.entriesTitle=group.group_id?`群 ${group.group_id}`:"全部圣经";el.entriesTitle.textContent=state.entriesTitle;renderGroups();loadEntries()});el.groupList.append(button)}}

function renderEntries(){el.entryList.replaceChildren();el.status.hidden=state.entries.length>0;el.status.textContent=state.total?"当前页没有条目。":"没有找到符合条件的圣经。";for(const item of state.entries){const article=document.createElement("article");article.className="entry";const id=document.createElement("div");id.className="entry-id";id.textContent=`#${item.id}`;const body=document.createElement("div");const head=document.createElement("div");head.className="entry-head";const author=document.createElement("span");author.className="entry-author";author.textContent=item.author_name;const meta=document.createElement("span");meta.className="entry-meta";meta.textContent=`QQ ${item.author_id} · ${formatTime(item.source_time)}`;head.append(author,meta);const text=document.createElement("div");text.className="entry-text";text.textContent=truncate(item.plain_text);const tags=document.createElement("div");tags.className="entry-tags";for(const label of [`群 ${item.group_id}`,`${item.image_count} 张图片`,`收录：${item.collector_name}`]){const tag=document.createElement("span");tag.className="tag";tag.textContent=label;tags.append(tag)}body.append(head,text,tags);const remove=document.createElement("button");remove.className="delete-button";remove.textContent="删除";remove.addEventListener("click",()=>deleteEntry(item));article.append(id,body,remove);el.entryList.append(article)}el.filteredMetric.textContent=state.total;el.pageLabel.textContent=`${state.page} / ${state.totalPages}`;el.previousButton.disabled=state.page<=1;el.nextButton.disabled=state.page>=state.totalPages}

async function loadEntries(){el.status.hidden=false;el.status.textContent="正在载入……";el.entryList.replaceChildren();try{const data=unwrap(await bridge.apiGet("manage/entries",{group_id:state.groupId,query:state.query,page:state.page,page_size:state.pageSize}));state.entries=data.entries;state.total=data.total;state.totalPages=data.total_pages;renderEntries()}catch(error){el.status.textContent=error.message;toast(error.message,"error")}}

async function loadBootstrap(){const data=unwrap(await bridge.apiGet("manage/bootstrap"));state.groups=data.groups;state.entries=data.entries;state.config=data.config;state.total=data.total;state.totalPages=data.total_pages;el.totalMetric.textContent=data.total;el.groupMetric.textContent=data.groups.length;renderGroups();renderEntries();fillSettings()}

async function deleteEntry(item){if(!window.confirm(`确定删除群 ${item.group_id} 的圣经 #${item.id}？此操作不可撤销。`))return;try{unwrap(await bridge.apiPost("manage/delete",{group_id:item.group_id,id:item.id}));toast(`已删除 #${item.id}`);await loadBootstrap();if(state.groupId||state.query)await loadEntries()}catch(error){toast(error.message,"error")}}

function fillSettings(){for(const [key,value] of Object.entries(state.config)){const input=el.settingsForm.elements.namedItem(key);if(!input)continue;if(input.type==="checkbox")input.checked=Boolean(value);else input.value=value??""}}
function settingsPayload(){const f=el.settingsForm.elements;return{add_permission_level:Number(f.add_permission_level.value),enable_poke_random:f.enable_poke_random.checked,poke_cooldown_seconds:Number(f.poke_cooldown_seconds.value),random_pool_copies:Number(f.random_pool_copies.value),random_pool_reset_minutes:Number(f.random_pool_reset_minutes.value),list_page_size:Number(f.list_page_size.value),max_text_length:Number(f.max_text_length.value),max_images:Number(f.max_images.value),show_bible_id:f.show_bible_id.checked}}

function bind(){let searchTimer;el.searchInput.addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=el.searchInput.value.trim();state.page=1;loadEntries()},280)});el.previousButton.addEventListener("click",()=>{if(state.page>1){state.page--;loadEntries()}});el.nextButton.addEventListener("click",()=>{if(state.page<state.totalPages){state.page++;loadEntries()}});el.refreshButton.addEventListener("click",async()=>{try{await loadBootstrap();toast("已刷新")}catch(error){toast(error.message,"error")}});el.settingsButton.addEventListener("click",()=>{fillSettings();el.settingsDialog.showModal()});el.closeSettingsButton.addEventListener("click",()=>el.settingsDialog.close());el.cancelSettingsButton.addEventListener("click",()=>el.settingsDialog.close());el.settingsForm.addEventListener("submit",async event=>{event.preventDefault();try{state.config=unwrap(await bridge.apiPost("manage/config",settingsPayload()));el.settingsDialog.close();toast("配置已保存")}catch(error){toast(error.message,"error")}})}

async function init(){if(!bridge){el.status.textContent="请从 AstrBot 插件管理页打开此页面。";return}try{if(typeof bridge.ready==="function")await bridge.ready();bind();await loadBootstrap()}catch(error){el.status.textContent=error.message||"页面初始化失败";toast(el.status.textContent,"error")}}
init();
